name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and build Geode mod
        id: build
        uses: geode-sdk/build-geode-mod@main
        with:
          target: Android64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod
          path: ${{ steps.build.outputs.build-output }}
          if-no-files-found: error
