name: Build Geode Mod

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and build Geode mod
        uses: geode-sdk/build-geode-mod@main
        with:
          target: pc

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: geode-mod
          path: build/**/*.geode
          if-no-files-found: warn
